### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Notadogtrainer** [msarnacki/flashscore-scraper#3]
I just ran the code, not very good with coding.. ehh... is this a me problem or some other problem? Really appreciate any help!

Traceback (most recent call last):
  File "/Users/admin/Desktop/master/main.py", line 160, in <module>
    urls = get_urls_xlsx(urls_path, data_path)
  File "/Users/admin/Desktop/master/main.py", line 93, in get_urls_xlsx
    url_league = url.split('/')[-4] + "_" + url.split('/')[-3]   
AttributeError: 'float' object has no attribute 'split'

**Comment by Notadogtrainer** [comment]
A me problem, resolved
